In [30]:
# Install torch and torchvision on your computer
# It's convenient to create a virtual env for that

In [31]:
import torch
import torch.nn as nn
import numpy as np

In [32]:
# set the torch manual seed to 42
torch.manual_seed(42)


In [33]:
# Create a tensor of shape (5,) and store in the features variable
features = torch.randn((5,))
features


tensor([ 0.3367,  0.1288,  0.2345,  0.2303, -1.1229])

In [34]:
# Generate a tensor called weights with the same shape of features
# Hint: search torch.rand_like
weights = torch.rand_like(features)

In [35]:
assert weights.shape == features.shape

In [36]:
weights

tensor([0.8694, 0.5677, 0.7411, 0.4294, 0.8854])

In [37]:
bias = torch.randn((1,1))

In [38]:
bias

tensor([[-0.1863]])

In [39]:
# Implement the sigmoid function by using torch
def sigmoid(x):
    return 1 / (1+torch.exp(x))

In [40]:
# Use torch.dot function for multiplying weights and features and
# add the bias to the result. Store the result into the score variable

score = torch.dot(features, weights) + bias
score



tensor([[-0.5420]])

In [41]:
assert score.shape == (1,1)

In [42]:
# Use the defined sigmoid function to activate the score.
# Store the result in the prob variable

prob = sigmoid(score)
prob


tensor([[0.6323]])

In [43]:
assert prob.shape == (1,1)

In [46]:
# Convert the a numpy array into a torch tensor
# Store it in the b variable
a = np.random.rand(4, 3)
a
b = torch.from_numpy(a)

In [47]:
assert b.shape == (4,3) 

In [50]:
# Do the opposite now. From the given tensor a convert it a numpy array
# Store the result in b
a = torch.tensor([1,2])
a
b = a.numpy()

In [51]:
assert type(b) == np.ndarray

In [52]:
# Reshape the given v tensor in a 10x10 tensor.
# Store the result in v_reshaped
# You can use various methods: reshape, view, resize... Check all of them

v = torch.randn((100,1))
v_reshaped = torch.reshape(v, (10,10))


In [53]:
# create a tensor with shape (16, 32, 32, 3) containing only ones
# Store it in the ones variable
ones = torch.ones(16, 32, 32, 3)


In [54]:
assert ones.shape == (16, 32, 32, 3)

In [55]:
import pandas as pd
import matplotlib.pyplot as plt
# load and plot the data using scatterplot with different colors for labels
data = pd.read_csv('data.csv', header=None)
data

0         1  2
0   0.78051 -0.063669  1
1   0.28774  0.291390  1
2   0.40714  0.178780  1
3   0.29230  0.421700  1
4   0.50922  0.352560  1
..      ...       ... ..
95  0.77029  0.701400  0
96  0.73156  0.717820  0
97  0.44556  0.579910  0
98  0.85275  0.859870  0
99  0.51912  0.623590  0

[100 rows x 3 columns]

TypeError: scatter() missing 1 required positional argument: 'y'