#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [21]:
import numpy as np

rand_array = np.random.randint(1, 100,(10,10))
maxelement = np.amax(rand_array)
minelement = np.amin(rand_array)
print(rand_array)
print(maxelement)
print(minelement)

[[31 71 10 52  1 10 55 40  2 18]
 [37 88  5  6 25 43 41 40 80  9]
 [20 95 44 47 86 23 25 19 90 46]
 [74 15 54 65 32 59 99  4 24  9]
 [23 20 35 14 22 35 13 75 44 99]
 [92 39 53 35 50 91 76 84 34 90]
 [74 50 66 38 62 96 28 92  2 62]
 [47 85 49 69 17 14 18 75 56 59]
 [88 53 31 52 39 25 13 33 88 36]
 [53 73 88 36 77 65 29 39 28 84]]
99
1


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [22]:
a = np.ones((10, 10))
a[1:-1, 1:-1] = 0
print(a) 

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
