#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [1]:
import numpy as np

rand_array = np.random.randint(1, 100,(10,10))
maxelement = np.amax(rand_array)
minelement = np.amin(rand_array)
print(rand_array)
print(maxelement)
print(minelement)

[[83 67 21 78 68 53 66 33 84 42]
 [18 84 52 93 60 74 94 89  2 25]
 [71 17 21 82 73 63 78 29 57 86]
 [89  7 55 15 16 93 65 35 35 61]
 [81 18 93 32 35  7 62 68 11 48]
 [ 9 12 45 43 82  1 56 40 82 14]
 [ 8 93 52 73 18 79  5 39 80 69]
 [85  2 48 31 22 14 24 89  7 36]
 [88 32 54 49 16 58  8  5 77 24]
 [84 24 49 77 75 53 79 64  1  9]]
94
1


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [3]:
a = np.ones((10, 10))
a[1:-1, 1:-1] = 0
print(a) 

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
