#### 72. How to swap two rows of an array? (★★★)

In [1]:
import numpy as np

a = np.array([[24, 88,  3, 23, 16, 41, 54, 13, 65, 61,], [13, 41, 58, 49, 18, 82, 20, 63, 81, 41], [90, 99, 49, 30, 81, 37, 17, 20, 40, 82], [61, 71, 95, 83, 48, 51, 85, 76, 76, 44], [35, 69,  4, 78, 78,  5, 53, 12, 43, 77]])
print('Before')
print(a)

a[[0, 2]] = a[[2, 0]]
print('After:')
print(a)

Before
[[24 88  3 23 16 41 54 13 65 61]
 [13 41 58 49 18 82 20 63 81 41]
 [90 99 49 30 81 37 17 20 40 82]
 [61 71 95 83 48 51 85 76 76 44]
 [35 69  4 78 78  5 53 12 43 77]]
After:
[[90 99 49 30 81 37 17 20 40 82]
 [13 41 58 49 18 82 20 63 81 41]
 [24 88  3 23 16 41 54 13 65 61]
 [61 71 95 83 48 51 85 76 76 44]
 [35 69  4 78 78  5 53 12 43 77]]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [12]:
import numpy as np

arr = np.array([24, 88,  3, 23, 16, 41, 54, 13, 65, 61])
d = list(range(0, 9)) + list(range(9,0,1))

np.convolve(arr, np.ones_like(arr)) / d
# np.convolve(arr, np.ones_like(arr), 'same')
# np.convolve(arr, np.ones_like(arr), 'full')



ValueError: operands could not be broadcast together with shapes (19,) (9,) 